name: flutter_inapp_purchase
description: In App Purchase plugin for Flutter, forked to support Billing Library 8.0.0.
version: 5.6.2
homepage: https://github.com/sorymohajer/flutterpuzzzzzzzzzzz

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  meta: ^1.12.0
  platform: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.25.7

flutter:
  plugin:
    platforms:
      android:
        package: com.dooboolab.flutterinapppurchase
        pluginClass: FlutterInappPurchasePlugin
        mainClass: FlutterInappPurchasePlugin
      ios:
        pluginClass: FlutterInappPurchasePlugin
